name: Terraform Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  TF_VERSION: "1.8.0"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config=config/backend.tf

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve -input=false -var-file="terraform.tfvars"
